language: python
python:
  - "3.6-dev" # 3.6 development branch
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy3"
  - "pypy"
#  - "3.1"  # not currently supported by Travis CI

install: true
#install:
#  - pip install xlrd
#  - pip install pandas

# command to run tests and check installation
script:
  - python setup.py test
  - python setup.py install
