language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "nightly"  # current CPython development build
  - "pypy3"
  - "pypy"
#  - "3.1"  # not currently supported by Travis CI

#install:
#  - pip install xlrd
#  - pip install pandas
#  - python setup.py install

# command to run tests
script: python setup.py test
